name: dbt_sumup
version: 2
profile: dbt-sumup

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]
log-path: "logs"
modules-path: "dbt_modules"
profiles.yml: "profiles.yml"
project-root: "."
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Configuración de los modelos
models:
  dbt-sumup:
    raw_data:
      enabled: true
      materialized: view
      schema: raw_data
      database: dbt-sumup
      quoting:
        identifier: true
    analysis:
      enabled: true
      materialized: view
      schema: analysis
      database: dbt-sumup
      quoting:
        identifier: true
    staging:
      enabled: true
      materialized: view
      schema: staging
      database: dbt-sumup
      quoting:
        identifier: true
    mart:
      enabled: true
      materialized: view
      schema: mart
      database: dbt-sumup
      quoting:
        identifier: true
