name: dbt_sumup
profile: dbt_sumup

version: 1.0

config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  dbt_sumup:
    staging:
      +materialized: view
    mart:
      +materialized: table
    reporting:
      +materialized: table