name: dbt_sumup
profile: dbt_sumup

version: 1.0

config-version: 2

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  pos_lite_project:
    raw_data:
      +materialized: view
    staging:
      +materialized: view
    mart:
      +materialized: table