name: dbt_sumup

model-paths: ["models"]  # Cambié 'source-paths' a 'model-paths'
analysis-paths: ["analysis"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]
log-path: "logs"
seed-paths: ["data"]  # Cambié 'data-paths' a 'seed-paths'
project-root: "."
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

profile: dbt_sumup

# Configuración de los modelos
models:
  dbt_sumup:
    raw_data:
      enabled: true
      materialized: view
      schema: raw_data
      database: dbt_sumup
      quoting:
        identifier: true
    analysis:
      enabled: true
      materialized: view
      schema: analysis
      database: dbt_sumup
      quoting:
        identifier: true
    staging:
      enabled: true
      materialized: view
      schema: staging
      database: dbt_sumup
      quoting:
        identifier: true
    mart:
      enabled: true
      materialized: view
      schema: mart
      database: dbt_sumup
      quoting:
        identifier: true
